version: '3'
services:
  db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres         
      ports:
        - "5433:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    build: bot/
    depends_on:
      - db
    environment:
      - DSN=postgresql+psycopg2://postgres:password@localhost:5433/postgres
      - BOT_KEY=
      - KEY=
    network_mode: host

volumes:
  db: