version: '3'
services:
  db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
      ports:
        - "5432:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    build:
      context: ./bot
    depends_on:
      - db
    volumes:
    - ../.env:/app/.env


volumes:
  db: