version: '3'
services:
  db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres         
      ports:
        - "5433:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    build: bot/
    depends_on:
      - db
    env_file:
      - .env
    network_mode: host

volumes:
  db: